linters-settings:
  gocritic:
    disabled-checks:
      - commentFormatting
    enabled-tags:
      - performance
      - diagnostic
      - style
      - opinionated

linters:
  enable-all: true
  disable:
    - nonamedreturns
    - exhaustruct
    - exhaustivestruct
    - gochecknoglobals
    - testpackage
    - exhaustive
    - varnamelen
    - forbidigo
    - goerr113
    - misspell
    - gofumpt
    - cyclop
    - gomnd
    - gci
  fast: false

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-rules:
    - path: stringers/random.go
      text: "G404" # G402: Use of weak random number generator.
      linters:
        - gosec
    - path: ._test\.go
      linters:
        - funlen
        - ifshort
        - cyclop
