run:
  allow-parallel-runners: true

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - nonamedreturns
    - exhaustruct
    - testpackage
    - varnamelen
    - depguard
    - intrange
    - ireturn
    - gofumpt

linters-settings:
  cyclop:
    max-complexity: 12
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - diagnostic
      - style

issues:
  exclude-rules:
    - path: stringers/random.go
      text: "G404" # G402: Use of weak random number generator.
      linters:
        - gosec
    - path: symtab.go
      linters:
        - misspell
