version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gochecknoglobals
    - intrange
    - ireturn
    - nonamedreturns
    - testpackage
    - varnamelen
    - noinlineerr
  settings:
    cyclop:
      max-complexity: 12
    errcheck:
      check-type-assertions: true
    gocritic:
      enabled-tags:
        - performance
        - opinionated
        - diagnostic
        - style
    govet:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: stringers/random.go
        text: G404
      - linters:
          - misspell
        path: symtab.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
