run:
  go: '1.19'

linters-settings:
  gocritic:
    disabled-checks:
      - commentFormatting
    enabled-tags:
      - performance
      - diagnostic
      - style
      - opinionated
  cyclop:
    max-complexity: 12

linters:
  enable-all: true
  disable:
    - nonamedreturns
    - exhaustruct
    - exhaustivestruct
    - gochecknoglobals
    - testpackage
    - varnamelen
  fast: false

output:
  format: 'colored-line-number'
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-rules:
    - path: stringers/random.go
      text: "G404" # G402: Use of weak random number generator.
      linters:
        - gosec
    - path: symtab.go
      linters:
        - misspell
    - path: ._test\.go
      linters:
        - ifshort
