# ci workflow
name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup golang
        uses: actions/setup-go@v6
        with:
          go-version: ^1.25
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
  test:
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup golang
        uses: actions/setup-go@v6
        with:
          go-version: ^1.25
      - name: run-test
        run: make test
      - name: push-coverage
        if: ${{ github.event_name == 'push' }}
        uses: qltysh/qlty-action/coverage@v2
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ${{ github.workspace }}/cover.out
  codeql:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: ci
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup golang
        uses: actions/setup-go@v6
        with:
          go-version: ^1.25
      - name: init codeql
        uses: github/codeql-action/init@v4
        with:
          languages: 'go'
      - name: run analysis
        uses: github/codeql-action/analyze@v4
      - name: update goreportcard
        uses: creekorful/goreportcard-action@v1.0
